apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: actions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/enatan-tenant/actions/actions@sha256:84265931d8a962c82b26e5e9e6574ec75715dd5821507ee4f1bcc67b043b9aea
        name: container-image
        resources: {}
status: {}
