apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: actions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: actions
    app.kubernetes.io/part-of: actions
  name: actions
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: actions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: actions
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/enatan-tenant/actions/actions@sha256:b303412de689764010e6e16fa4ad42cafff6b8ad7d7e275f95062624f85cb7b7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
